### ISSUE TITLE
Horribly slow

### ISSUE THREAD

**Issue by Chinay-Domitrix** [Badbird-5907/i-hate.school#3]
We _may_ want to work on speeding up the site…
[Google Lighthouse result](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fi-hate.school%2F)

**Comment by Badbird5907** [comment]
dosen't really matter lmao, this is just a placeholder site

**Comment by Chinay-Domitrix** [comment]
fair

**Comment by Chinay-Domitrix** [comment]
> dosen't really matter lmao, this is just a placeholder site

speaking of which, are you actually working on the site or no?

**Comment by Badbird5907** [comment]
no i'm not, its was just a meme
